/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BrowseJobsRouteImport } from './routes/browse-jobs'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as CompanySubmissionsRouteImport } from './routes/company/submissions'
import { Route as CompanySettingsRouteImport } from './routes/company/settings'
import { Route as CompanyProposalsRouteImport } from './routes/company/proposals'
import { Route as CompanyMessagesRouteImport } from './routes/company/messages'
import { Route as CompanyJobsRouteImport } from './routes/company/jobs'
import { Route as CompanyInterviewsRouteImport } from './routes/company/interviews'
import { Route as CompanyCandidatesRouteImport } from './routes/company/candidates'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseJobsRoute = BrowseJobsRouteImport.update({
  id: '/browse-jobs',
  path: '/browse-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySubmissionsRoute = CompanySubmissionsRouteImport.update({
  id: '/company/submissions',
  path: '/company/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/company/settings',
  path: '/company/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProposalsRoute = CompanyProposalsRouteImport.update({
  id: '/company/proposals',
  path: '/company/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyMessagesRoute = CompanyMessagesRouteImport.update({
  id: '/company/messages',
  path: '/company/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/company/jobs',
  path: '/company/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyInterviewsRoute = CompanyInterviewsRouteImport.update({
  id: '/company/interviews',
  path: '/company/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/company/candidates',
  path: '/company/candidates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/browse-jobs': typeof BrowseJobsRoute
  '/companies': typeof CompaniesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/proposals': typeof CompanyProposalsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/submissions': typeof CompanySubmissionsRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/browse-jobs': typeof BrowseJobsRoute
  '/companies': typeof CompaniesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/proposals': typeof CompanyProposalsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/submissions': typeof CompanySubmissionsRoute
  '/company': typeof CompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/browse-jobs': typeof BrowseJobsRoute
  '/companies': typeof CompaniesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/proposals': typeof CompanyProposalsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/submissions': typeof CompanySubmissionsRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/browse-jobs'
    | '/companies'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/company/candidates'
    | '/company/interviews'
    | '/company/jobs'
    | '/company/messages'
    | '/company/proposals'
    | '/company/settings'
    | '/company/submissions'
    | '/company/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/browse-jobs'
    | '/companies'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/company/candidates'
    | '/company/interviews'
    | '/company/jobs'
    | '/company/messages'
    | '/company/proposals'
    | '/company/settings'
    | '/company/submissions'
    | '/company'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/browse-jobs'
    | '/companies'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/company/candidates'
    | '/company/interviews'
    | '/company/jobs'
    | '/company/messages'
    | '/company/proposals'
    | '/company/settings'
    | '/company/submissions'
    | '/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BrowseJobsRoute: typeof BrowseJobsRoute
  CompaniesRoute: typeof CompaniesRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRoute
  CompanyInterviewsRoute: typeof CompanyInterviewsRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyMessagesRoute: typeof CompanyMessagesRoute
  CompanyProposalsRoute: typeof CompanyProposalsRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  CompanySubmissionsRoute: typeof CompanySubmissionsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-jobs': {
      id: '/browse-jobs'
      path: '/browse-jobs'
      fullPath: '/browse-jobs'
      preLoaderRoute: typeof BrowseJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/submissions': {
      id: '/company/submissions'
      path: '/company/submissions'
      fullPath: '/company/submissions'
      preLoaderRoute: typeof CompanySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/company/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/proposals': {
      id: '/company/proposals'
      path: '/company/proposals'
      fullPath: '/company/proposals'
      preLoaderRoute: typeof CompanyProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/messages': {
      id: '/company/messages'
      path: '/company/messages'
      fullPath: '/company/messages'
      preLoaderRoute: typeof CompanyMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs': {
      id: '/company/jobs'
      path: '/company/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/interviews': {
      id: '/company/interviews'
      path: '/company/interviews'
      fullPath: '/company/interviews'
      preLoaderRoute: typeof CompanyInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/company/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  BrowseJobsRoute: BrowseJobsRoute,
  CompaniesRoute: CompaniesRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
  CompanyCandidatesRoute: CompanyCandidatesRoute,
  CompanyInterviewsRoute: CompanyInterviewsRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyMessagesRoute: CompanyMessagesRoute,
  CompanyProposalsRoute: CompanyProposalsRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  CompanySubmissionsRoute: CompanySubmissionsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
